### ISSUE TITLE
Serialize query string showing when livewire component field is updated.

### ISSUE THREAD

**Issue by kaozaza2** [tabuna/breadcrumbs#34] opened 2022-08-04 04:18 UTC
Hi

Sometime library showing url query, how to disable it?

![image](https://user-images.githubusercontent.com/11665930/182761997-cba74d47-b5bf-4873-ab29-3f205d09cdd9.png)

**Edit:**
laravel/framework : 9.22.1
livewire/livewire: 2.10.6
tabuna/breadcrumbs: 3.0.0

**Comment by tabuna** [comment] 2022-08-04 09:45
Hello, can you give more information on how to reproduce this behavior?

**Comment by kaozaza2** [comment] 2022-08-04 11:25
This happen on livewire form field has updated.

route/web.php
```php
Route::get('/models/{model}/update', LivewireModelFormUpdate::class)
    ->name('model.update')
    ->breadcrumbs(fn (Trail $trail, Model $model) => $trail->parent('model.index')->push('Update', route('model.update', $model)));
```

LivewireModelFormUpdate.php
```php
class LivewireModelFormUpdate extends Component
{
    public Model $model;

    public function mount(Model $model)
    {
        $this->model = $model;
    }
    //...
}
```

model-form-update.blade.php
```php
<div>
    <x-custom-breadcrumb />
    <form wire:submit.prevent="store">
        <input wire:model="model.name" type="text" />
    </form>
</div>
```

custom-breadcrumb.blade.php
```php
@if(Breadcrumbs::has())
    <ul>
    @foreach (Breadcrumbs::current() as $crumbs)
        @if ($crumbs->url() && !$loop->last)
            <li>
                <a href="{{ $crumbs->url() }}">
                    {{ $crumbs->title() }}
                </a>
            </li>
        @else
            <li>
                <p>{{ $crumbs->title() }}</p>
            </li>
        @endif
    @endforeach
    </ul>
@endif
```

**Comment by tabuna** [comment] 2022-08-04 11:58
It looks like livewire doesn't run the middleware on this route, as it goes the other way. Most likely this can be fixed by adding middleware to the web group ([It is used by default in livewire](https://github.com/livewire/livewire/blob/master/config/livewire.php#L84)). 

To do this, go to `app/Http/Kernel.php` and add:

```php
protected $middlewareGroups = [
    'web' => [
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        \App\Http\Middleware\VerifyCsrfToken::class,
        \Illuminate\Routing\Middleware\SubstituteBindings::class,

        \Tabuna\Breadcrumbs\BreadcrumbsMiddleware::class, // it row
    ],
];
```

**Comment by kaozaza2** [comment] 2022-08-05 06:02
> 

Tried, still same.

**Comment by kaozaza2** [comment] 2022-08-10 12:01
Can you fix it?

**Comment by kaozaza2** [comment] 2022-10-13 19:13
Not fixed.

**Closed** 2022-10-13 19:13 UTC

**Comment by aspross** [comment] 2023-03-08 16:35
Hello, i have the same error right now. Any solution?

**Comment by tabuna** [comment] 2023-03-08 21:22
@aspross You can use the definition separately from the route. [Example](https://github.com/tabuna/breadcrumbs#route-resource):

```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Tabuna\Breadcrumbs\Breadcrumbs;
use Tabuna\Breadcrumbs\Trail;

class BreadcrumbsServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Breadcrumbs::for('photos.index', fn (Trail $trail) =>
             $trail->push('Photos', route('home'))
        );
        
        Breadcrumbs::for('photos.create', fn (Trail $trail) =>
            $trail
                ->parent('photos.index', route('photos.index'))
                ->push('Add new photo', route('home'))
        );
    }
}
```

It runs even before the middleware is passed from the livewire
